#==============================================================================
#description     :This makefile carries out all necessary calculations
#                :related to the 'test_banana_pairwise' test
#author          :Piotr Majka, Konrad Solarz
#date            :2014-09-30
#usage           :make all
#==============================================================================

all: step1

step1:
	bash -x step_001_deformable_reconstruction.sh

clean:
	rm -rf deformable_reconstruction_result.nii.gz
